language: python
python:
  - "3.5"
before_install:
    - pip install pytest

# Build config files
script:
  - pytest basic_checks.py
  - python build.py

# Upload config files to S3
addons:
  artifacts:
    target_paths: /tdsConfig
