FROM unidata/tds-buildconfig:v4.6.4-SNAPSHOT
MAINTAINER Ryan May <rmay@ucar.edu>

# SECRET keys for accessing S3
ENV s3fs_access_key="" s3fs_secret_key="" AWS_ACCESS_KEY_ID="" AWS_SECRET_ACCESS_KEY=""
